// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkApbJ3e_K8oFAg1-o-iS8gIdNhFOVPzY',
    appId: '1:509724216292:web:2704757d000654b0b715f1',
    messagingSenderId: '509724216292',
    projectId: 'dataclevers01',
    authDomain: 'dataclevers01.firebaseapp.com',
    storageBucket: 'dataclevers01.appspot.com',
    measurementId: 'G-KZL43B5EBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2gum5zItfQWRg0e2NTX3xnZ_IhqatreE',
    appId: '1:509724216292:android:0f92e8195f1397fab715f1',
    messagingSenderId: '509724216292',
    projectId: 'dataclevers01',
    storageBucket: 'dataclevers01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMOPwnrujdzDqmEkzg2KzrLU9jjCM1gsA',
    appId: '1:509724216292:ios:f6cbb73c1eeb9b5eb715f1',
    messagingSenderId: '509724216292',
    projectId: 'dataclevers01',
    storageBucket: 'dataclevers01.appspot.com',
    iosClientId: '509724216292-arhls46m4vp7mm4av2nlra4r2g425cnm.apps.googleusercontent.com',
    iosBundleId: 'com.example.aptitudes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMOPwnrujdzDqmEkzg2KzrLU9jjCM1gsA',
    appId: '1:509724216292:ios:f6cbb73c1eeb9b5eb715f1',
    messagingSenderId: '509724216292',
    projectId: 'dataclevers01',
    storageBucket: 'dataclevers01.appspot.com',
    iosClientId: '509724216292-arhls46m4vp7mm4av2nlra4r2g425cnm.apps.googleusercontent.com',
    iosBundleId: 'com.example.aptitudes',
  );
}
